name: check for new odo version

on:
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run updater
        run: $GITHUB_WORKSPACE/tools/version-update -token ${{ secrets.GITHUB_TOKEN }} -formulaFile $GITHUB_WORKSPACE/Formula/odo.rb -repo odo -org openshift
      - name: Create commits
        run: |
          git config user.name 'Tomas Kral'
          git config user.email 'tomas.kral@gmail.com'
          git status
          git commit -a -m "auto update formula"
          git status
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          base: master
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"